name: Fly build and deploy

on:
  pull_request:
  push:
    branches:
    - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP_NAME: ${{ vars.FLY_APP_NAME }}
  FLY_REGION: ${{ vars.FLY_REGION }}
  FLY_REGIONS: ${{ vars.FLY_REGIONS }}

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: markiannucci/flyctl-actions/setup-flyctl@main

      - id: update-app-name-for-prs
        if: github.event_name == 'pull_request'
        run: 
          echo "FLY_APP_NAME=${FLY_APP_NAME}-${{ github.event.number }}" >> $GITHUB_ENV

      - id: variable-substition
        run : |
          envsubst < fly.template.toml | tee fly.toml
          envsubst < config.template.yaml | tee config.yaml
          envsubst < ./terraform/terraform.template.tfvars | tee ./terraform/terraform.tfvars
          rm ./terraform/terraform.template.tfvars # delete this so tf fmt doesn't fail
      
      # terraform boilerplate stuff
      - id: tf-setup
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - id: tf-fmt
        run: terraform fmt -check
        working-directory: ./terraform
        continue-on-error: true
      - id: fix-tf-fmt
        if: steps.tf-fmt.outcome == 'failure'
        run: |
          git fetch origin ${{ github.head_ref }}
          git checkout ${{ github.head_ref }}
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          terraform fmt
          git add .
          git commit -m "fix terraform format "
          git push
        working-directory: ./terraform
      - id: tf-init
        run: terraform init
        working-directory: ./terraform
      - id: tf-validate
        run: terraform validate -no-color
        working-directory: ./terraform
      - id: tf-workspace
        if: github.event_name == 'pull_request'
        run: |
          if [ -z "$(terraform workspace list | grep ${{ github.event.number }} )" ]; then
            terraform workspace new ${{ github.event.number }}
          else
            terraform workspace select ${{ github.event.number }}
          fi

      - id: tf-apply 
        run: terraform apply -auto-approve -input=false
        working-directory: ./terraform

      # scale fly app to zero if running
      - id: scale-zero
        run: |
          if [ $(flyctl status --json | jq ".Status") -eq '"running"' ]; then 
            flyctl scale count 0
            sleep 60
          fi

      # deploy to first region
      - id: deploy
        run: flyctl deploy --region $(echo "$FLY_REGIONS" | cut -d',' -f1)

      # scale to other regions
      - id: scale-out
        run: flyctl scale count 3 --max-per-region 1

      - id: tf-plan-production
        if: github.event_name == 'pull_request'
        run: |
          # cleanup the FLY_APP_NAME we polluted earlier
          HYPHENS=$(echo "$FLY_APP_NAME" | tr -cd '-' | wc -c)
          FLY_APP_NAME=$(echo "FLY_APP_NAME" | cut -d'-' -f1-$HYPHENS) 

          # rerun the envsubst
          envsubst < terraform.template.tfvars | tee terraform.tfvars

          # hack around initial workspace loss
          if [ -z "$(terraform workspace list | grep default )" ]; then
            terraform workspace new default
          else
            terraform workspace select default
          fi
          terraform plan -no-color -input=false
        working-directory: ./terraform
