name: Fly build and deploy

on:
  pull_request:
  push:
    branches:
    - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP_NAME: ${{ vars.FLY_APP_NAME }}
  FLY_REGION: ${{ vars.FLY_REGION }}
  FLY_REGIONS: ${{ vars.FLY_REGIONS }}

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: markiannucci/flyctl-actions/setup-flyctl@main

      - id: update-app-name-for-prs
        if: github.event_name == 'pull_request'
        run: 
          echo "FLY_APP_NAME=${FLY_APP_NAME}-${{ github.event.number }}" >> $GITHUB_ENV

      - id: variable-substition
        run : |
          envsubst < fly.template.toml | tee fly.toml
          envsubst < config.template.yaml | tee config.yaml
          envsubst < ./terraform/terraform.template.tfvars | tee ./terraform/terraform.tfvars
          rm ./terraform/terraform.template.tfvars # delete this so tf fmt doesn't fail
      
      # terraform boilerplate stuff
      - id: tf-setup
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - id: tf-fmt
        run: terraform fmt -check
        working-directory: ./terraform
        continue-on-error: true
      - id: fix-tf-fmt
        if: steps.tf-fmt.outcome == 'failure'
        run: |
          git fetch origin ${{ github.head_ref }}
          git checkout ${{ github.head_ref }}
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          terraform fmt
          git add .
          git commit -m "fix terraform format "
          git push
        working-directory: ./terraform
      - id: tf-init
        run: terraform init
        working-directory: ./terraform
      - id: tf-validate
        run: terraform validate -no-color
        working-directory: ./terraform
      - id: tf-workspace
        if: github.event_name == 'pull_request'
        run: |
          if [ -z "$(terraform workspace list | grep ${{ github.event.number }} )" ]; then
            terraform workspace new ${{ github.event.number }}
          else
            terraform workspace select ${{ github.event.number }}
          fi

      - id: tf-apply 
        run: terraform apply -auto-approve -input=false
        working-directory: ./terraform

      - id: deploy
        run: flyctl deploy --remote-only --region ${FLY_REGION} 

      - id: tf-plan-production
        if: github.event_name == 'pull_request'
        run: |
          terraform workspace select default
          terraform plan -no-color -input=false
        working-directory: ./terraform
