name: Cleanup fly

on:
  pull_request:
    types:
      - closed

env:
  ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY}}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP_NAME: ${{ vars.FLY_APP_NAME || secrets.FLY_APP_NAME }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: markiannucci/flyctl-actions/setup-flyctl@main

      - id: update-app-name-for-prs
        if: github.event_name == 'pull_request'
        run: 
          echo "FLY_APP_NAME=${FLY_APP_NAME}-${{ github.event.number }}" >> $GITHUB_ENV
      
      - id: destroy-app
        run:
          flyctl apps destroy ${FLY_APP_NAME} --yes

      - id: tf-setup
        uses: hashicorp/setup-terraform@v2
      - id: cleanup-terraform-workspace
        run: |
          terraform init
          terraform workspace delete -force $FLY_APP_NAME
        working-directory: ./terraform
