name: Cleanup fly

on:
  pull_request:
    types:
      - closed

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP_NAME: ${{ vars.FLY_APP_NAME }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: markiannucci/flyctl-actions/setup-flyctl@main

      - id: update-app-name-for-prs
        if: github.event_name == 'pull_request'
        run: 
          echo "FLY_APP_NAME=${FLY_APP_NAME}-${{ github.event.number }}" >> $GITHUB_ENV
      
      - id: destroy-app
        run:
          flyctl apps destroy ${FLY_APP_NAME} --yes
